# tip: 频率
frequency:
  - { label: RF0, value: 500000 }
  - { label: RF1, value: 7000000 }
  - { label: RF2, value: 7500000 }
  - { label: RF3, value: 8000000 }
  - { label: RF4, value: 8500000 }
  - { label: RF5, value: 9000000 }
  - { label: RF6, value: 9500000 }
  - { label: RF7, value: 10000000 }
  - { label: RF8, value: 10500000 }
  - { label: RF9, value: 11000000 }
  - { label: RF10, value: 11500000 }
  - { label: RF11, value: 12000000 }
  - { label: RF12, value: 12500000 }
  - { label: RF13, value: 37000000 }
  - { label: RF14, value: 37500000 }
  - { label: RF15, value: 38000000 }
  - { label: RF16, value: 38500000 }
  - { label: RF17, value: 39000000 }
  - { label: RF18, value: 39500000 }
  - { label: RF19, value: 40000000 }
  - { label: RF20, value: 40500000 }
